"""
Pydantic schemas for Asset validation.

These schemas define:
- What data clients must send (Create)
- What data clients can update (Update)
- What data the API returns (Response)
"""

# Import the enum from models to reuse it
# This ensures API accepts same values as database
from app.models import AssetClass
from pydantic import BaseModel, ConfigDict, Field


class AssetBase(BaseModel):
    """
    Base schema with fields common to Create and Response.

    This is not used directly — other schemas inherit from it.
    """

    ticker: str = Field(
        ...,  # ... means required
        min_length=1,
        max_length=10,
        examples=["AAPL", "MSFT", "BTC-USD"],
        description="Trading symbol (e.g., 'AAPL' for Apple)"
    )

    exchange: str | None = Field(
        ...,
        max_length=10,
        examples=["NASDAQ", "NYSE", "XETRA"],
        description="Stock exchange where the asset is traded"
    )

    # Optional fields (can be None)
    isin: str | None = Field(
        default=None,
        min_length=12,
        max_length=12,
        pattern=r"^[A-Z]{2}[A-Z0-9]{10}$",  # ISIN format: 2 letters + 10 alphanumeric
        examples=["US0378331005"],
        description="International Securities Identification Number"
    )

    name: str | None = Field(
        default=None,
        max_length=255,
        examples=["Apple Inc.", "Microsoft Corporation"],
        description="Full name of the asset"
    )

    asset_class: AssetClass = Field(
        ...,
        description="Type of asset",
        examples=[AssetClass.STOCK, AssetClass.ETF]
    )

    currency: str = Field(
        default="EUR",
        min_length=3,
        max_length=3,
        pattern=r"^[A-Z]{3}$",  # ISO 4217 currency code
        examples=["EUR", "USD", "GBP"],
        description="Currency the asset is priced in (ISO 4217)"
    )

    sector: str | None = Field(
        default=None,
        max_length=100,
        examples=["Technology", "Healthcare", "Financial Services"],
        description="Industry sector"
    )

    region: str | None = Field(
        default=None,
        max_length=100,
        examples=["North America", "Europe", "Asia Pacific"],
        description="Geographic region"
    )


class AssetCreate(AssetBase):
    """
    Schema for creating a new asset.

    Inherits all fields from AssetBase.
    No 'id' field — the database generates it.
    """

    # is_active defaults to True for new assets
    is_active: bool = Field(
        default=True,
        description="Whether the asset is currently active/tradeable"
    )


class AssetUpdate(BaseModel):
    """
    Schema for updating an existing asset.

    All fields are optional — client only sends fields to update.
    This is called a "partial update" or "PATCH" pattern.
    """

    ticker: str | None = Field(
        default=None,
        min_length=1,
        max_length=10
    )

    asset_class: AssetClass | None = Field(default=None)

    isin: str | None = Field(
        default=None,
        min_length=12,
        max_length=12,
        pattern=r"^[A-Z]{2}[A-Z0-9]{10}$"
    )

    name: str | None = Field(default=None, max_length=255)
    exchange: str | None = Field(default=None, max_length=50)

    currency: str | None = Field(
        default=None,
        min_length=3,
        max_length=3,
        pattern=r"^[A-Z]{3}$"
    )

    sector: str | None = Field(default=None, max_length=100)
    region: str | None = Field(default=None, max_length=100)
    is_active: bool | None = Field(default=None)


class AssetResponse(AssetBase):
    """
    Schema for API responses.

    Includes 'id' which is generated by the database.
    Includes 'is_active' to show current status.
    """

    id: int = Field(..., description="Unique identifier")
    is_active: bool = Field(..., description="Whether the asset is currently active")

    # This tells Pydantic to read data from SQLAlchemy models
    # Without this, returning a SQLAlchemy object would fail
    model_config = ConfigDict(from_attributes=True)
