"""Make asset_id nullable for DEPOSIT/WITHDRAWAL

Revision ID: 9fa4a978ee74
Revises: b2c3d4e5f678
Create Date: 2026-01-17 10:22:26.045900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa4a978ee74'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'asset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'asset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
