"""Phase 3: Add exchange_rates, sync_status, portfolio_settings

Revision ID: e8193cc7257e
Revises: 70daaa7f2061
Create Date: 2026-01-15 18:13:13.884703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8193cc7257e'
down_revision: Union[str, Sequence[str], None] = 'daa490ca3288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'quote_currency', 'date', name='uq_exchange_rate_pair_date')
    )
    op.create_index('ix_exchange_rate_lookup', 'exchange_rates', ['base_currency', 'quote_currency', 'date'], unique=False)
    op.create_index(op.f('ix_exchange_rates_base_currency'), 'exchange_rates', ['base_currency'], unique=False)
    op.create_index(op.f('ix_exchange_rates_date'), 'exchange_rates', ['date'], unique=False)
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.create_index(op.f('ix_exchange_rates_quote_currency'), 'exchange_rates', ['quote_currency'], unique=False)
    op.create_table('portfolio_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('enable_proxy_backcasting', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_settings_id'), 'portfolio_settings', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_settings_portfolio_id'), 'portfolio_settings', ['portfolio_id'], unique=True)
    op.create_table('sync_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('last_sync_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('NEVER', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'PENDING', name='syncstatusenum'), nullable=False),
    sa.Column('coverage_summary', sa.JSON(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_status_id'), 'sync_status', ['id'], unique=False)
    op.create_index(op.f('ix_sync_status_portfolio_id'), 'sync_status', ['portfolio_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_status_portfolio_id'), table_name='sync_status')
    op.drop_index(op.f('ix_sync_status_id'), table_name='sync_status')
    op.drop_table('sync_status')
    op.drop_index(op.f('ix_portfolio_settings_portfolio_id'), table_name='portfolio_settings')
    op.drop_index(op.f('ix_portfolio_settings_id'), table_name='portfolio_settings')
    op.drop_table('portfolio_settings')
    op.drop_index(op.f('ix_exchange_rates_quote_currency'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_date'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_base_currency'), table_name='exchange_rates')
    op.drop_index('ix_exchange_rate_lookup', table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
